server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5433/fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true